// Agent Dashboard/src/components/common/ThemeToggle.vue
<template>
  <q-btn
    type="button"
    flat
    round
    :icon="themeStore.isDark ? 'light_mode' : 'dark_mode'"
    :size="size === 'sm' ? 'sm' : 'md'"
    @click="themeStore.toggleTheme"
    aria-label="Toggle theme"
    :title="themeStore.isDark ? 'Switch to light' : 'Switch to dark'"
  />
</template>

<script setup lang="ts">
import { useThemeStore } from '@/app/theme/themeStore'

interface Props {
  size?: 'sm' | 'md'
}

withDefaults(defineProps<Props>(), {
  size: 'sm',
})

const themeStore = useThemeStore()
</script>

  );
}

// Agent Dashboard/src/components/common/ThemeToggle.tsx
import React from "react";
import { Moon, Sun } from "lucide-react";
import { useTheme } from "../../app/theme/ThemeProvider";
import { Button } from "../ui/Button";

export function ThemeToggle({ size = "sm" }: { size?: "sm" | "md" }) {
  const { theme, toggleTheme } = useTheme();
  const Icon = theme === "dark" ? Sun : Moon;

  return (
    <Button
      type="button"
      variant="ghost"
      size={size === "sm" ? "sm" : "md"}
      onClick={toggleTheme}
      aria-label="Toggle theme"
      title={theme === "dark" ? "Switch to light" : "Switch to dark"}
    >
      <Icon className="h-4 w-4" />
    </Button>
  );
}
