// Agent Dashboard/src/app/shell/DashboardLayout.tsx
import React, { useEffect, useState } from "react";
import { Outlet, useNavigate } from "react-router-dom";
import { useAuthStore } from "../auth/authStore";
import { Button } from "../../components/ui/Button";
import { ThemeToggle } from "../../components/common/ThemeToggle";
import { Menu } from "lucide-react";
import { Sidebar } from "./Sidebar";

export function DashboardLayout() {
  const user = useAuthStore((s) => s.user);
  const logout = useAuthStore((s) => s.logout);
  const navigate = useNavigate();

  const STORAGE_KEY = "clazino_sidebar_collapsed";
  const [collapsed, setCollapsed] = useState<boolean>(() => {
    const v = localStorage.getItem(STORAGE_KEY);
    return v === "1"; // default expanded
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, collapsed ? "1" : "0");
  }, [collapsed]);

  const [mobileOpen, setMobileOpen] = useState(false);

  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="flex">
        <Sidebar
          userName={user?.name}
          clanName={user?.clanName}
          collapsed={collapsed}
          mobileOpen={mobileOpen}
          setMobileOpen={setMobileOpen}
          onLogout={logout}
        />

        <main className="flex-1">
          <header className="sticky top-0 z-40 border-b border-border bg-background/80 backdrop-blur">
            <div className="mx-auto max-w-[1400px] px-5 py-4 flex items-center justify-between gap-4">
              <div className="flex items-center gap-2">
                {/* Mobile menu */}
                <div className="md:hidden">
                  <Button
                    size="icon"
                    variant="ghost"
                    onClick={() => setMobileOpen(true)}
                    aria-label="Open sidebar"
                    title="Open sidebar"
                  >
                    <Menu className="h-4 w-4" />
                  </Button>
                </div>
                {/* Desktop sidebar toggle */}
                <div className="hidden md:block">
                  <Button
                    size="icon"
                    variant="ghost"
                    onClick={() => setCollapsed((p) => !p)}
                    aria-label="Toggle sidebar"
                    title={collapsed ? "Expand sidebar" : "Collapse sidebar"}
                  >
                    <Menu className="h-4 w-4" />
                  </Button>
                </div>

                <div>
                  <div className="text-xs text-muted-foreground">Agent</div>
                  <div className="text-sm font-semibold">{user?.clanName ?? "Clan"}</div>
                </div>
              </div>

              <div className="flex items-center gap-1">
                <ThemeToggle />
                <Button size="sm" variant="secondary" onClick={() => navigate("/dashboard/invites")}>Invite Player</Button>
                <Button size="sm" variant="secondary" onClick={() => navigate("/dashboard/wallet")}>Deposit USDT</Button>
              </div>
            </div>
          </header>

          <div className="mx-auto max-w-[1400px] px-5 py-6">
            <Outlet />
          </div>
        </main>
      </div>
    </div>
  );
}

// Agent Dashboard/src/app/shell/DashboardLayout.vue
<template>
  <div class="min-h-screen bg-background text-foreground">
    <div class="flex">
      <Sidebar
        :userName="user?.name"
        :clanName="user?.clanName"
        :collapsed="collapsed"
        :mobileOpen="mobileOpen"
        @toggle-mobile="mobileOpen = $event"
        @logout="handleLogout"
      />

      <main class="flex-1">
        <header class="sticky top-0 z-40 border-b border-border bg-background/80 backdrop-blur">
          <div class="mx-auto max-w-[1400px] px-5 py-4 flex items-center justify-between gap-4">
            <div class="flex items-center gap-2">
              <!-- Mobile menu -->
              <div class="md:hidden">
                <q-btn
                  flat
                  round
                  icon="menu"
                  size="md"
                  @click="mobileOpen = true"
                  aria-label="Open sidebar"
                  title="Open sidebar"
                />
              </div>
              <!-- Desktop sidebar toggle -->
              <div class="hidden md:block">
                <q-btn
                  flat
                  round
                  icon="menu"
                  size="md"
                  @click="collapsed = !collapsed"
                  :title="collapsed ? 'Expand sidebar' : 'Collapse sidebar'"
                  aria-label="Toggle sidebar"
                />
              </div>

              <div>
                <div class="text-xs text-muted-foreground">Agent</div>
                <div class="text-sm font-semibold">{{ user?.clanName ?? 'Clan' }}</div>
              </div>
            </div>

            <div class="flex items-center gap-1">
              <ThemeToggle />
              <q-btn
                size="sm"
                flat
                @click="$router.push('/dashboard/invites')"
              >
                Invite Player
              </q-btn>
              <q-btn
                size="sm"
                flat
                @click="$router.push('/dashboard/wallet')"
              >
                Deposit USDT
              </q-btn>
            </div>
          </div>
        </header>

        <div class="mx-auto max-w-[1400px] px-5 py-6">
          <RouterView />
        </div>
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../auth/authStore'
import Sidebar from './Sidebar.vue'
import ThemeToggle from '@/components/common/ThemeToggle.vue'
import { RouterView } from 'vue-router'

const authStore = useAuthStore()
const router = useRouter()

const user = computed(() => authStore.user)

const STORAGE_KEY = 'clazino_sidebar_collapsed'
const collapsed = ref<boolean>(() => {
  const v = localStorage.getItem(STORAGE_KEY)
  return v === '1'
}())

const mobileOpen = ref(false)

watch(collapsed, (value) => {
  localStorage.setItem(STORAGE_KEY, value ? '1' : '0')
})

const handleLogout = () => {
  authStore.logout()
  router.push('/login')
}
</script>
